/**
 * PHASE 27 — MACRO REGIME TEST FIXTURES
 * =====================================
 * TEST-ONLY deterministic observation vintage. These values previously lived in
 * the production service (`getCanonicalMacroObservations`) as frozen samples;
 * they are explicitly NOT production data and must never be served as a live
 * statutory feed (P27-D2). Production reads `macro_observations` via
 * DrizzleMacroRegimeDataSource and fails closed to UNKNOWN when empty.
 *
 * TEMPORAL COHERENCE (P27-D3): every publicationDate is <= the 2026-09-30
 * observation date, so the default test asOfDate never self-triggers
 * lookahead rejection.
 */

import type { MacroObservation } from '../../../lib/macro-regime/index.ts';

export function getFixtureMacroObservations(asOfDate = '2026-09-30'): MacroObservation[] {
  const retrievalDate = asOfDate;
  return [
    {
      metricCode: 'VN_GDP_GROWTH',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-29',
      retrievalDate,
      value: 6.82,
      unit: '% YoY',
      source: 'Tổng cục Thống kê (GSO)',
      sourceTier: 'TIER_1_STATUTORY',
      revisionVersion: 0,
      frequency: 'QUARTERLY',
      periodId: '2026-Q3',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Tăng trưởng GDP thực tế quý 3/2026',
    },
    {
      metricCode: 'VN_CPI',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-29',
      retrievalDate,
      value: 3.45,
      unit: '% YoY',
      source: 'Tổng cục Thống kê (GSO)',
      sourceTier: 'TIER_1_STATUTORY',
      revisionVersion: 0,
      frequency: 'MONTHLY',
      periodId: '2026-09',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Chỉ số giá tiêu dùng bình quân tháng 9/2026',
    },
    {
      metricCode: 'VN_CORE_CPI',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-29',
      retrievalDate,
      value: 2.71,
      unit: '% YoY',
      source: 'Tổng cục Thống kê (GSO)',
      sourceTier: 'TIER_1_STATUTORY',
      revisionVersion: 0,
      frequency: 'MONTHLY',
      periodId: '2026-09',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Lạm phát cơ bản loại trừ lương thực và năng lượng',
    },
    {
      metricCode: 'VN_PMI',
      observationDate: '2026-09-30',
      // P27-D3: fixture vintage is publication-coherent (publication <= observation).
      publicationDate: '2026-09-30',
      retrievalDate,
      value: 51.5,
      unit: 'Points',
      source: 'S&P Global Vietnam Manufacturing PMI',
      sourceTier: 'TIER_2_EXCHANGE',
      revisionVersion: 0,
      frequency: 'MONTHLY',
      periodId: '2026-09',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Chỉ số nhà quản trị mua hàng ngành sản xuất',
    },
    {
      metricCode: 'SBV_REFINANCING_RATE',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-30',
      retrievalDate,
      value: 4.5,
      unit: '%',
      source: 'Ngân hàng Nhà nước Việt Nam (SBV)',
      sourceTier: 'TIER_1_STATUTORY',
      revisionVersion: 0,
      frequency: 'EVENT_DRIVEN',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Lãi suất tái cấp vốn điều hành',
    },
    {
      metricCode: 'VN_DEPOSIT_RATE',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-30',
      retrievalDate,
      value: 4.95,
      unit: '%',
      source: 'SBV / Big 4 Bank Survey',
      sourceTier: 'TIER_1_STATUTORY',
      revisionVersion: 0,
      frequency: 'MONTHLY',
      periodId: '2026-09',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Lãi suất tiền gửi bình quân 12 tháng',
    },
    {
      metricCode: 'USD_VND',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-30',
      retrievalDate,
      value: 24860,
      unit: 'VND',
      source: 'SBV / Vietcombank',
      sourceTier: 'TIER_1_STATUTORY',
      revisionVersion: 0,
      frequency: 'DAILY',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Tỷ giá USD/VND liên ngân hàng',
    },
    {
      metricCode: 'US_DXY',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-30',
      retrievalDate,
      value: 102.8,
      unit: 'Points',
      source: 'Intercontinental Exchange (ICE)',
      sourceTier: 'TIER_2_EXCHANGE',
      revisionVersion: 0,
      frequency: 'DAILY',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Chỉ số US Dollar Index',
    },
    {
      metricCode: 'US_10Y_YIELD',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-30',
      retrievalDate,
      value: 4.08,
      unit: '%',
      source: 'US Treasury',
      sourceTier: 'TIER_1_STATUTORY',
      revisionVersion: 0,
      frequency: 'DAILY',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Lợi suất trái phiếu chính phủ Mỹ 10 năm',
    },
    {
      metricCode: 'US_2Y_YIELD',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-30',
      retrievalDate,
      value: 3.96,
      unit: '%',
      source: 'US Treasury',
      sourceTier: 'TIER_1_STATUTORY',
      revisionVersion: 0,
      frequency: 'DAILY',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Lợi suất trái phiếu chính phủ Mỹ 2 năm',
    },
    {
      metricCode: 'GLOBAL_VIX',
      observationDate: '2026-09-30',
      publicationDate: '2026-09-30',
      retrievalDate,
      value: 18.2,
      unit: 'Points',
      source: 'CBOE',
      sourceTier: 'TIER_2_EXCHANGE',
      revisionVersion: 0,
      frequency: 'DAILY',
      validationStatus: 'VALID',
      freshnessStatus: 'CURRENT',
      notes: 'Chỉ số biến động CBOE VIX',
    },
  ];
}
