/**
 * PHASE 6 — ENTERPRISE INTELLIGENCE ENGINE
 * =========================================
 * Stable TypeScript contract for the structured result produced by the
 * deterministic financial analysis engines and consumed by the AI Analyst UI.
 *
 * STRICT RULES:
 *   - Every financial value is `number | null`. `null` ALWAYS means
 *     "data unavailable" — NEVER zero, NEVER a guess, NEVER an average.
 *   - Every calculated metric is deterministic (pure functions).
 *   - The LLM only interprets this structured result; it never invents numbers.
 */

/** Confidence about a single metric / evidence item. */
export type EvidenceConfidence = 'HIGH' | 'MEDIUM' | 'LOW';

/** Overall confidence for the full result. */
export type ConfidenceLevel = 'HIGH' | 'MEDIUM' | 'LOW';

/** Classification of the enterprise score. */
export type ScoreClassification =
  | 'EXCEPTIONAL'
  | 'STRONG'
  | 'GOOD'
  | 'NEUTRAL'
  | 'WEAK'
  | 'RISKY'
  | 'PROVISIONAL';

/** Growth classification labels. */
export type GrowthClassification = 'STRONG' | 'HEALTHY' | 'MODERATE' | 'WEAK' | 'DECLINING';

/** Risk level labels shared by financial health and risk engine. */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/** Earnings quality classification. */
export type EarningsQualityClassification =
  | 'PROFIT_SUPPORTED_BY_CASH'
  | 'PROFIT_PARTIALLY_SUPPORTED'
  | 'LOW_CASH_CONVERSION';

/** Sentiment-like investment view (not a buy/sell recommendation). */
export type InvestmentView = 'VERY_POSITIVE' | 'POSITIVE' | 'NEUTRAL' | 'CAUTIOUS' | 'NEGATIVE';

/**
 * Evidence contract — lets the UI answer "WHY?" for any major conclusion.
 */
export interface AnalysisEvidence {
  metric: string;
  value: number | string | null;
  period: string | null;
  source: string;
  calculation: string | null;
  confidence: ConfidenceLevel;
}

/** An alert generated by the deterministic alert engine. */
export interface EnterpriseAlert {
  id: string;
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
  metric: string;
  value: number | null;
  threshold: number | null;
  reason: string;
}

// ---------------------------------------------------------------------------
// ENGINES 1..10
// ---------------------------------------------------------------------------

export interface BusinessQualityResult {
  score: number | null;
  businessModelQuality: number | null;
  industryAttractiveness: number | null;
  competitiveAdvantage: number | null;
  revenueQuality: number | null;
  growthVisibility: number | null;
  risks: string[];
}

export interface GrowthResult {
  score: number | null;
  revenueYoY: number | null;
  revenueCAGR3Y: number | null;
  revenueCAGR5Y: number | null;
  profitYoY: number | null;
  profitCAGR3Y: number | null;
  epsGrowth: number | null;
  fcfGrowth: number | null;
  growthAcceleration: number | null;
  classification: GrowthClassification | null;
}

export interface ProfitabilityResult {
  score: number | null;
  grossMargin: number | null;
  operatingMargin: number | null;
  netMargin: number | null;
  roe: number | null;
  roa: number | null;
  roic: number | null;
  trends: {
    marginChange: number | null;
    roeTrend: number | null;
    roaTrend: number | null;
    roicTrend: number | null;
  };
}

export interface FinancialHealthResult {
  score: number | null;
  currentRatio: number | null;
  quickRatio: number | null;
  debtToEquity: number | null;
  netDebt: number | null;
  netDebtToEBITDA: number | null;
  interestCoverage: number | null;
  cashToDebt: number | null;
  debtGrowth: number | null;
  riskLevel: RiskLevel | null;
}

export interface EarningsQualityResult {
  score: number | null;
  cfo: number | null;
  fcf: number | null;
  cfoMargin: number | null;
  fcfMargin: number | null;
  cashConversion: number | null;
  accrualRatio: number | null;
  receivablesGrowth: number | null;
  inventoryGrowth: number | null;
  qualityClassification: EarningsQualityClassification | null;
  warnings: string[];
}

export interface DupontThreeFactor {
  netProfitMargin: number | null;
  assetTurnover: number | null;
  equityMultiplier: number | null;
  calculatedROE: number | null;
  reportedROE: number | null;
  reconciliationDifference: number | null;
}

export interface DupontFiveFactor {
  taxBurden: number | null;
  interestBurden: number | null;
  operatingMargin: number | null;
  assetTurnover: number | null;
  financialLeverage: number | null;
  calculatedROE: number | null;
}

export interface DupontResult {
  threeFactor: DupontThreeFactor;
  fiveFactor: DupontFiveFactor;
  primaryROEDriver: 'margin' | 'assetEfficiency' | 'leverage' | null;
}

export interface PiotroskiCriterion {
  id: string;
  name: string;
  value: number | null;
  previousValue: number | null;
  passed: boolean | null;
  reason: string;
  dataAvailable: boolean;
}

export interface PiotroskiResult {
  total: number | null;
  maxAvailable: number;
  normalizedScore: number | null;
  profitability: number | null;
  leverageLiquidity: number | null;
  operatingEfficiency: number | null;
  criteria: PiotroskiCriterion[];
}

export interface ValuationIntelligenceResult {
  score: number | null;
  pe: number | null;
  pb: number | null;
  evEbitda: number | null;
  historicalPEPercentile: number | null;
  historicalPBPercentile: number | null;
  peerPEPremiumDiscount: number | null;
  peerPBPremiumDiscount: number | null;
  dcfFairValue: number | null;
  peFairValue: number | null;
  pbFairValue: number | null;
  marginOfSafety: number | null;
  currentPrice: number | null;
}

export interface CompetitiveResult {
  score: number | null;
  rank: number | null;
  peerCount: number;
  growthRank: number | null;
  profitabilityRank: number | null;
  valuationRank: number | null;
  financialHealthRank: number | null;
  peers: Array<{
    symbol: string;
    name?: string | null;
    value: number | null;
    rank: number;
  }>;
}

export interface RiskCatalystResult {
  overall: RiskLevel | null;
  score: number | null;
  business: number | null;
  industry: number | null;
  financial: number | null;
  valuation: number | null;
  earnings: number | null;
  cashFlow: number | null;
  market: number | null;
  catalysts: string[];
  risks: Array<{
    category: string;
    score: number;
    level: RiskLevel;
    reason: string;
    evidence: string | null;
    dataDate: string | null;
    confidence: ConfidenceLevel;
  }>;
}

export interface MarketIntelligenceResult {
  score: number | null;
  technicalTrend: string | null;
  momentum: string | null;
  moneyFlow: string | null;
  foreignFlow: string | null;
  price: number | null;
  dataDate: string | null;
  source: string | null;
}

// ---------------------------------------------------------------------------
// ENTERPRISE SCORE + SCENARIOS + THESIS + AGGREGATE RESULT
// ---------------------------------------------------------------------------

export interface EnterpriseScoreResult {
  total: number | null;
  classification: ScoreClassification | null;
  confidence: ConfidenceLevel | null;
  dataCompleteness: number | null;
  isProvisional: boolean;
  breakdown: {
    businessQuality: number;
    growth: number;
    profitability: number;
    financialHealth: number;
    earningsQuality: number;
    valuation: number;
    competitive: number;
    marketTechnical: number;
    riskAdjustment: number;
  };
  availableMetrics: string[];
  missingMetrics: string[];
}

export interface ScenarioResult {
  case: 'bull' | 'base' | 'bear';
  fairValue: number | null;
  upside: number | null;
  growth: number | null;
  margin: number | null;
  multiple: number | null;
  probability: number;
  reasoning: string | null;
}

export interface ScenarioSetResult {
  bull: ScenarioResult;
  base: ScenarioResult;
  bear: ScenarioResult;
  expectedValue: number | null;
  consistent: boolean;
}

export interface InvestmentThesisResult {
  conclusion: InvestmentView | null;
  strengths: string[];
  risks: string[];
  catalysts: string[];
  bullCase: string | null;
  baseCase: string | null;
  bearCase: string | null;
  invalidationConditions: string[];
  watchItems: string[];
}

export interface AIInterpretationResult {
  summary: string | null;
  strengths: string[];
  risks: string[];
  catalysts: string[];
  bullCase: string | null;
  baseCase: string | null;
  bearCase: string | null;
  invalidationConditions: string[];
  watchItems: string[];
  conclusion: string | null;
  confidence: ConfidenceLevel | null;
  generatedBy: 'deterministic-analyst' | 'llm' | null;
  model: string | null;
  llmAvailable: boolean;
}

/** Data quality summary. */
export interface DataQualitySummary {
  completeness: number;
  confidence: ConfidenceLevel;
  financialPeriods: number;
  marketDataAvailable: boolean;
  missingMetrics: string[];
}

/**
 * Top-level structured result of the Enterprise Intelligence Engine.
 */
export interface EnterpriseIntelligenceResult {
  symbol: string;
  generatedAt: string;
  asOfDate: string | null;
  currency: 'VND';

  dataQuality: DataQualitySummary;

  businessQuality: BusinessQualityResult;
  growth: GrowthResult;
  profitability: ProfitabilityResult;
  financialHealth: FinancialHealthResult;
  earningsQuality: EarningsQualityResult;
  dupont: DupontResult;
  piotroski: PiotroskiResult;
  valuation: ValuationIntelligenceResult;
  competitive: CompetitiveResult;
  marketIntelligence: MarketIntelligenceResult;
  risk: RiskCatalystResult;

  enterpriseScore: EnterpriseScoreResult;

  scenarios: ScenarioSetResult;

  investmentThesis: InvestmentThesisResult;
  aiInterpretation: AIInterpretationResult;

  evidence: AnalysisEvidence[];
  alerts: EnterpriseAlert[];
  timeline: Array<{
    year: number;
    revenue: number | null;
    netProfit: number | null;
    eps: number | null;
    cfo: number | null;
    fcf: number | null;
    roe: number | null;
    roic: number | null;
    debt: number | null;
    grossMargin: number | null;
    netMargin: number | null;
  }>;
}