/**
 * PHASE 17.6 — STRATEGY BACKTEST & HISTORICAL VERIFICATION TYPES
 * ==============================================================
 * Pure TypeScript contracts for historical backtesting and statistical verification.
 * 
 * STRICT RULES:
 *   - No look-ahead bias: Strategy evaluation context is strictly bounded to T <= current.
 *   - Fail-closed validation: Invalid prices, negative quantities, or non-finite values reject.
 *   - Zero mock data in production: All real data originates from real market providers.
 */

import type { InvestmentHorizon } from '../../../types/recommendation.ts';

/**
 * Validated historical candlestick point
 */
export interface HistoricalCandle {
  readonly symbol: string;
  readonly timestamp: string; // ISO 8601 Date "YYYY-MM-DD" or full ISO
  readonly open: number;
  readonly high: number;
  readonly low: number;
  readonly close: number;
  readonly volume: number;
  readonly value?: number | null;
}

/**
 * Historical evaluation context passed to strategies at step `currentIndex`
 * Strictly prevents reading future candles index > currentIndex.
 */
export interface HistoricalContext {
  readonly symbol: string;
  readonly currentIndex: number;
  readonly currentCandle: HistoricalCandle;
  /** Sliced history up to and including currentIndex (0...currentIndex) */
  readonly candlesToDate: readonly HistoricalCandle[];
  readonly totalCandles: number;
}

/**
 * Actionable trading signal generated by a backtested strategy at candle T close
 */
export type BacktestSignalAction = 'BUY' | 'SELL' | 'HOLD';

export interface BacktestSignal {
  readonly action: BacktestSignalAction;
  readonly reason: string;
  readonly confidence: number; // 0.0 to 1.0
  readonly stopLoss?: number | null;
  readonly takeProfit?: number | null;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

/**
 * Interface that all backtestable strategies must implement
 */
export interface HistoricalStrategy {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly horizon?: InvestmentHorizon;
  readonly minLookback: number;

  /**
   * Evaluates signal at candle T close using historical context up to T.
   * MUST NOT access future candles.
   */
  evaluate(context: HistoricalContext): BacktestSignal;
}

/**
 * Backtest execution configuration
 */
export interface BacktestConfig {
  readonly symbol: string;
  readonly initialCapital: number;
  /** Brokerage commission rate on trade value (default: 0.0015 = 0.15%) */
  readonly commissionRate?: number;
  /** Slippage rate on trade price (default: 0.0010 = 0.10%) */
  readonly slippageRate?: number;
  /** Vietnam sell tax rate (default: 0.0010 = 0.10%) */
  readonly sellTaxRate?: number;
  /** Capital allocation per trade as percentage of equity (default: 1.0 = 100% or 0.20 = 20%) */
  readonly positionSizePct?: number;
  /** Maximum holding period in trading sessions (optional) */
  readonly maxHoldingDays?: number;
  /** Stop loss threshold percentage below entry (e.g. 0.07 = 7%) */
  readonly stopLossPct?: number;
  /** Take profit threshold percentage above entry (e.g. 0.15 = 15%) */
  readonly takeProfitPct?: number;
  /** Vietnam standard board lot size (default: 100) */
  readonly boardLot?: number;
  /** Custom timeframe label (e.g. '1D', '1Y') */
  readonly timeframe?: string;
}

/**
 * Reason for exiting a position in backtest
 */
export type BacktestExitReason =
  | 'STRATEGY_SIGNAL'
  | 'STOP_LOSS'
  | 'TAKE_PROFIT'
  | 'MAX_HOLDING_REACHED'
  | 'END_OF_DATA';

/**
 * Executed backtest trade record
 */
export interface BacktestTrade {
  readonly id: string;
  readonly symbol: string;
  readonly side: 'LONG';
  
  readonly entryDate: string;
  readonly entryPrice: number; // Execution price at T+1 open (with slippage)
  readonly entryGrossValue: number;
  readonly entryCommission: number;
  
  readonly exitDate: string;
  readonly exitPrice: number;  // Execution price at T+1 open (with slippage)
  readonly exitGrossValue: number;
  readonly exitCommission: number;
  readonly exitTax: number;
  
  readonly quantity: number;
  readonly grossPnL: number;
  readonly netPnL: number;
  readonly returnPct: number;
  readonly holdingDays: number;
  readonly exitReason: BacktestExitReason;
}

/**
 * Equity point tracking portfolio value at each candle
 */
export interface EquityPoint {
  readonly date: string;
  readonly cash: number;
  readonly positionValue: number;
  readonly totalEquity: number;
  readonly drawdownPct: number;
}

/**
 * Complete statistical performance metrics result
 */
export interface BacktestPerformanceMetrics {
  readonly initialCapital: number;
  readonly finalCapital: number;
  readonly netProfit: number;
  readonly totalReturnPct: number;

  readonly totalTrades: number;
  readonly winningTrades: number;
  readonly losingTrades: number;
  readonly breakEvenTrades: number;
  readonly winRatePct: number;

  readonly grossProfit: number;
  readonly grossLoss: number;
  readonly profitFactor: number | null;

  readonly averageTradeReturnPct: number;
  readonly averageWinReturnPct: number;
  readonly averageLossReturnPct: number;
  readonly winLossRatio: number | null;

  readonly maxDrawdownPct: number;
  readonly maxDrawdownAmount: number;
  readonly averageHoldingDays: number;

  readonly sharpeRatio: number | null;
  readonly sortinoRatio: number | null;
  readonly cagrPct: number | null;

  readonly totalCommissionPaid: number;
  readonly totalTaxPaid: number;
}

/**
 * Validation flags attached to backtest output
 */
export interface BacktestValidationAudit {
  readonly lookAheadBiasDetected: boolean;
  readonly invalidDataDetected: boolean;
  readonly deterministic: boolean;
  readonly errorMessages: readonly string[];
  readonly warningMessages: readonly string[];
}

/**
 * Comprehensive Backtest Result Output
 */
export interface BacktestResult {
  readonly symbol: string;
  readonly strategyId: string;
  readonly strategyName: string;
  readonly timeframe: string;
  readonly startDate: string;
  readonly endDate: string;
  readonly totalBars: number;

  readonly metrics: BacktestPerformanceMetrics;
  readonly trades: readonly BacktestTrade[];
  readonly equityCurve: readonly EquityPoint[];
  readonly validation: BacktestValidationAudit;
}
